# Generated by Django 6.1.1 on 2026-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_alter_neighbourhood_city_alter_neighbourhood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Квартал'),
        ),
    ]
