# Generated by Django 6.1.1 on 2026-10-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_name'),
        ('neighbourhood', '0003_alter_neighbourhood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Квартал'),
        ),
        migrations.AddConstraint(
            model_name='neighbourhood',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_neighbourhood_per_city'),
        ),
    ]
