# Generated by Django 6.1.1 on 2026-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
