# Generated by Django 6.1.1 on 2026-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_alter_broker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='description',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brokers/', verbose_name='Снимка'),
        ),
    ]
