# Generated by Django 6.1.1 on 2026-09-22 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_broker_description_alter_broker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Моля въведете 10-цифрен номер без интервали', regex='^\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
