# Generated by Django 6.1.1 on 2026-10-09 19:06

import myhome.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_broker_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brokers/', validators=[myhome.validators.ImageSizeValidator('Размерът на снимката трябва да е по-малък от 1MB.'), myhome.validators.ImageTypeValidator('Форматът на снимката трябва да е jpg, jpeg или png.')], verbose_name='Снимка'),
        ),
    ]
