# Generated by Django 6.1.1 on 2026-09-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('FOR_SALE', 'За продажба'), ('FOR_RENT', 'Под наем')], default='FOR_SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'Къща'), ('APARTMENT', 'Апартамент'), ('OFFICE', 'Офис'), ('STUDIO', 'Студио'), ('COMMERCIAL', 'Търговски обект'), ('GARAGE', 'Гараж'), ('PLOT', 'Plot')], default='APARTMENT', max_length=20),
        ),
    ]
