# Generated by Django 6.1.1 on 2026-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
        ('property', '0002_property_offer_type_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='feature.feature'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'Къща'), ('APARTMENT', 'Апартамент'), ('OFFICE', 'Офис'), ('STUDIO', 'Студио'), ('COMMERCIAL', 'Търговски обект'), ('GARAGE', 'Гараж'), ('PLOT', 'Парцел')], default='APARTMENT', max_length=20),
        ),
    ]
