# Generated by Django 6.1.1 on 2026-09-26 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_broker_phone_number'),
        ('feature', '0001_initial'),
        ('neighbourhood', '0002_alter_neighbourhood_city_alter_neighbourhood_name'),
        ('property', '0003_property_features_alter_property_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бани'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Спални'),
        ),
        migrations.AlterField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='broker.broker', verbose_name='Брокер'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='feature.feature', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood', verbose_name='Квартал'),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('FOR_SALE', 'За продажба'), ('FOR_RENT', 'Под наем')], default='FOR_SALE', max_length=20, verbose_name='Тип оферта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'Къща'), ('APARTMENT', 'Апартамент'), ('OFFICE', 'Офис'), ('STUDIO', 'Студио'), ('COMMERCIAL', 'Търговски обект'), ('GARAGE', 'Гараж'), ('PLOT', 'Парцел')], default='APARTMENT', max_length=20, verbose_name='Тип имот'),
        ),
    ]
