# Generated by Django 6.1.1 on 2026-09-27 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_main_image_alter_property_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(10)], verbose_name='Площ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(10)], verbose_name='Цена'),
        ),
    ]
