# Generated by Django 6.1.1 on 2026-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_area_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активна оферта'),
        ),
    ]
